[metadata]
project = "A realtime facial filter in python"
author = "YomamaBanana"
date = 2021-11-28
license = "Whatever you want to do with it"

# Tables
[camera]
index = 0
frame_width = 640
frame_height = 480
fps = 30

[mediapipe]
color = [0, 255, 0]
thickness = 1
circle_radius = 1
min_detection_confidence = 0.5
min_tracking_confidence = 0.5